### ISSUE TITLE
error: unable to resolve comptime value

### ISSUE THREAD

**Issue by TheLazyTurtle33** [tr1ckydev/chameleon#6]
I am new to zig so I'm probably just using the library wrong but I cant figure this out so any help is appreciated.
I am making a custom logger with colour.
my code:
```
 14     pub fn Print(self: Logger, s: []const u8) !void {
 15         comptime var cham = Chameleon.init(.Auto);
 16         if (self.level == LogLevel.Info or self.level == LogLevel.All) {
 17             std.debug.print(cham.white().fmt(s), .{});
 18         }
 19     }
```
the error:
```
src\Logger.zig:17:46: error: unable to resolve comptime value
src\Logger.zig:17:46: note: argument to function being called at comptime must be comptime-known   
```

**Comment by Book-reader** [comment]
you can fix this by making `s` comptime
```zig
pub fn Print(self: Logger, comptime s: []const u8) !void {
    comptime var cham = Chameleon.init(.Auto);
    if (self.level == LogLevel.Info or self.level == LogLevel.All) {
        std.debug.print(cham.white().fmt(s), .{});
    }
}
```
also `Print` does not have to be `!void` because (at least in the provided code snippet) nothing here can return an error.
`!void` would be needed if you were printing to `std.io.getStdOut().writer()`  but because `std.debug.print()` ignores any possible errors it is not needed
